theme: jekyll-theme-slate

# --- General options --- #

# Name of website
title: Qin Alliance

# Short description of your site
description: Qin Alliance is the largest nonprofit association representing the qin practice community. <br/>路上有琴
